# ------------------------------------------------------------------------------
#          NOTE: THIS DOCKERFILE IS GENERATED BY OCI IMAGES PROJECT
#
#                       PLEASE DO NOT EDIT IT DIRECTLY.
# ------------------------------------------------------------------------------
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

RUN microdnf install libaio -y \
	;mkdir -p /opt/oracle;
COPY /instantclient_21_5 /opt/oracle/instantclient_21_5
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_21_5

WORKDIR /opt/app
RUN chown 1001 /opt/app; \
    chmod "g+rwX" /opt/app; \
    chown 1001:root /opt/app;
	
USER 1001

EXPOSE 8080 8443 8778

ENTRYPOINT [ "/bin/bash" ]